const TILE_SIZE_M = 2.5;
const GRID_COLS = 35;
const GRID_ROWS = 25;

const LAYOUT_CONFIG = {
  layoutId: "u_shape_40_rooms",
  roomCount: 40,
  wingA: { roomCount: 20, labels: "A-01..A-20" },
  wingB: { roomCount: 20, labels: "B-01..B-20" },
  singleWingCorridorLengthM: 55,
  corridorWidthM: 2.8,
  roomAreaM2: 25,
  bathroomAreaM2: 4,
  roomCenterDistanceM: 4.5,
  nurseStationLocation: "U_BASE_CENTER",
  activityAreaEachEndM2: 50,
  equipmentStorageLocation: "U_BASE_RIGHT",
};

const PEAK_WINDOWS = {
  full_day: {
    label: "Full Day",
    start: "00:00",
    end: "24:00",
    sourceWindow: "00:00-24:00",
    defaultDurationTicks: 1440,
    taskMix: { light: 0.28, medium: 0.44, heavy: 0.28 },
    dominantTasks: ["patrol", "water", "medication", "feeding", "toileting", "turning"],
  },
  morning_peak: {
    label: "Morning Peak",
    start: "06:30",
    end: "08:30",
    sourceWindow: "06:30-09:00",
    defaultDurationTicks: 120,
    taskMix: { light: 0.2, medium: 0.45, heavy: 0.35 },
    dominantTasks: ["getting_up", "washing", "toileting", "transfer"],
  },
  midday_peak: {
    label: "Midday Peak",
    start: "10:30",
    end: "12:30",
    sourceWindow: "10:30-13:00",
    defaultDurationTicks: 120,
    taskMix: { light: 0.25, medium: 0.55, heavy: 0.2 },
    dominantTasks: ["meal_delivery", "feeding", "pre_meal_toileting", "medication"],
  },
  evening_peak: {
    label: "Evening Peak",
    start: "17:00",
    end: "19:00",
    sourceWindow: "17:00-21:00",
    defaultDurationTicks: 120,
    taskMix: { light: 0.2, medium: 0.4, heavy: 0.4 },
    dominantTasks: ["dinner", "pre_sleep_washing", "turning", "cleaning"],
  },
  evening_intensive: {
    label: "Evening Intensive",
    start: "17:00",
    end: "18:30",
    sourceWindow: "17:00-18:30",
    defaultDurationTicks: 90,
    taskMix: { light: 0.15, medium: 0.4, heavy: 0.45 },
    dominantTasks: ["dinner", "transfer", "cleaning", "turning"],
  },
};

const CONGESTION_CONFIG = {
  low: {
    label: "Low Congestion",
    speedReductionRatio: 0.2,
    passageTimeIncreaseRatio: 0.2,
    visualBadge: "低拥堵",
  },
  medium: {
    label: "Medium Congestion",
    speedReductionRatio: 0.35,
    passageTimeIncreaseRatio: 0.35,
    visualBadge: "中拥堵",
  },
  high: {
    label: "High Congestion",
    speedReductionRatio: 0.5,
    passageTimeIncreaseRatio: 0.5,
    visualBadge: "高拥堵",
  },
};

const SHIFT_CONFIG = {
  day_shift: {
    label: "Day Shift",
    time: "06:00-14:00",
    defaultWorkerCount: 6,
    minWorkerCount: 4,
    maxWorkerCount: 6,
    defaultDistribution: { wingA: 3, wingB: 3 },
  },
  evening_shift: {
    label: "Evening Shift",
    time: "14:00-22:00",
    defaultWorkerCount: 6,
    minWorkerCount: 4,
    maxWorkerCount: 6,
    defaultDistribution: { wingA: 3, wingB: 3 },
  },
  night_shift: {
    label: "Night Shift",
    time: "22:00-06:00",
    defaultWorkerCount: 2,
    minWorkerCount: 2,
    maxWorkerCount: 4,
    defaultDistribution: { wingA: 1, wingB: 1 },
  },
};

const DAY_WORKER_INITIAL_POSITIONS = [
  { id: "Worker-01", wing: "A", tile: { x: 9, y: 5 }, label: "A-Base" },
  { id: "Worker-02", wing: "A", tile: { x: 10, y: 12 }, label: "A-Mid" },
  { id: "Worker-03", wing: "A", tile: { x: 10, y: 20 }, label: "A-End" },
  { id: "Worker-04", wing: "B", tile: { x: 24, y: 5 }, label: "B-Base" },
  { id: "Worker-05", wing: "B", tile: { x: 25, y: 12 }, label: "B-Mid" },
  { id: "Worker-06", wing: "B", tile: { x: 17, y: 22 }, label: "Nurse-Station" },
  { id: "Worker-07", wing: "FULL", tile: { x: 15, y: 22 }, label: "Float-1" },
  { id: "Worker-08", wing: "FULL", tile: { x: 19, y: 22 }, label: "Float-2" },
];

const NIGHT_WORKER_INITIAL_POSITIONS = [
  { id: "Worker-N1", wing: "A", tile: { x: 9, y: 12 }, label: "A-Patrol" },
  { id: "Worker-N2", wing: "B", tile: { x: 24, y: 12 }, label: "B-Patrol" },
  { id: "Worker-N3", wing: "FULL", tile: { x: 17, y: 22 }, label: "Nurse-Station" },
  { id: "Worker-N4", wing: "FULL", tile: { x: 20, y: 22 }, label: "Storage-Base" },
];

const DEFAULT_WORKER_PROFILE = {
  baseWalkingSpeedMPerMinMin: 50,
  baseWalkingSpeedMPerMinMax: 70,
  initialFatigue: 0.0,
  fatigueMin: 0.0,
  fatigueMax: 1.0,
  unavailableFatigueThreshold: 0.85,
  warningFatigueThreshold: 0.65,
  maxConcurrentTasksDefault: 1,
};

const SENIOR_DISTRIBUTION_DEFAULT = {
  total: 40,
  careLevel1Low: 16,
  careLevel2Medium: 14,
  careLevel3High: 10,
};

const CARE_LEVEL_TASK_PROBABILITY = {
  1: { label: "Low", light: 0.65, medium: 0.25, heavy: 0.1 },
  2: { label: "Medium", light: 0.3, medium: 0.5, heavy: 0.2 },
  3: { label: "High", light: 0.15, medium: 0.25, heavy: 0.6 },
};

const SENIOR_INITIAL_STATUS = {
  health: {
    level1: { min: 70, max: 95 },
    level2: { min: 55, max: 85 },
    level3: { min: 35, max: 75 },
  },
  mood: {
    level1: { min: 60, max: 90 },
    level2: { min: 50, max: 85 },
    level3: { min: 40, max: 80 },
  },
  patience: {
    level1: { min: 55, max: 90 },
    level2: { min: 45, max: 80 },
    level3: { min: 35, max: 75 },
  },
  currentStatus: "idle",
};

const DEMAND_INTENSITY_CONFIG = {
  low: {
    label: "Low",
    expectedCallsPerHour: 8,
    minIntervalTicks: 5,
    maxIntervalTicks: 10,
    concurrentBurstMin: 1,
    concurrentBurstMax: 3,
  },
  medium: {
    label: "Medium",
    expectedCallsPerHour: 14,
    minIntervalTicks: 3,
    maxIntervalTicks: 7,
    concurrentBurstMin: 2,
    concurrentBurstMax: 5,
  },
  high: {
    label: "High",
    expectedCallsPerHour: 22,
    minIntervalTicks: 2,
    maxIntervalTicks: 5,
    concurrentBurstMin: 3,
    concurrentBurstMax: 8,
  },
  overcooked: {
    label: "Overcooked Stress Test",
    expectedCallsPerHour: 32,
    minIntervalTicks: 1,
    maxIntervalTicks: 3,
    concurrentBurstMin: 3,
    concurrentBurstMax: 8,
  },
};

const TASK_CATALOG = {
  patrol: {
    labelZh: "巡视",
    taskClass: "light",
    durationMin: 2,
    durationMode: 3,
    durationMax: 5,
    basePriority: 1,
    requiredWorkers: 1,
    requiredEquipment: [],
    fatigueIncrement: 0.005,
    healthDeltaOnComplete: 1,
    moodDeltaOnComplete: 1,
    patienceRestore: 8,
  },
  water: {
    labelZh: "饮水",
    taskClass: "light",
    durationMin: 2,
    durationMode: 3,
    durationMax: 4,
    basePriority: 2,
    requiredWorkers: 1,
    requiredEquipment: [],
    fatigueIncrement: 0.01,
    healthDeltaOnComplete: 1,
    moodDeltaOnComplete: 2,
    patienceRestore: 10,
  },
  fetch_item: {
    labelZh: "取物",
    taskClass: "light",
    durationMin: 2,
    durationMode: 3.5,
    durationMax: 5,
    basePriority: 2,
    requiredWorkers: 1,
    requiredEquipment: [],
    fatigueIncrement: 0.012,
    healthDeltaOnComplete: 0,
    moodDeltaOnComplete: 3,
    patienceRestore: 10,
  },
  medication: {
    labelZh: "用药提醒",
    taskClass: "light",
    durationMin: 2,
    durationMode: 4,
    durationMax: 5,
    basePriority: 4,
    requiredWorkers: 1,
    requiredEquipment: ["medicine_cart"],
    fatigueIncrement: 0.012,
    healthDeltaOnComplete: 5,
    moodDeltaOnComplete: 1,
    patienceRestore: 12,
  },
  feeding: {
    labelZh: "喂饭",
    taskClass: "medium",
    durationMin: 8,
    durationMode: 12,
    durationMax: 15,
    basePriority: 3,
    requiredWorkers: 1,
    requiredEquipment: [],
    fatigueIncrement: 0.035,
    healthDeltaOnComplete: 3,
    moodDeltaOnComplete: 4,
    patienceRestore: 18,
  },
  toileting: {
    labelZh: "如厕协助",
    taskClass: "medium",
    durationMin: 6,
    durationMode: 10,
    durationMax: 15,
    basePriority: 4,
    requiredWorkers: 1,
    requiredEquipment: ["commode_trolley"],
    fatigueIncrement: 0.04,
    healthDeltaOnComplete: 2,
    moodDeltaOnComplete: 4,
    patienceRestore: 18,
  },
  turning: {
    labelZh: "翻身",
    taskClass: "medium",
    durationMin: 6,
    durationMode: 8,
    durationMax: 12,
    basePriority: 3,
    requiredWorkers: 1,
    requiredEquipment: [],
    fatigueIncrement: 0.035,
    healthDeltaOnComplete: 4,
    moodDeltaOnComplete: 3,
    patienceRestore: 16,
  },
  cleaning: {
    labelZh: "清洁护理",
    taskClass: "heavy",
    durationMin: 12,
    durationMode: 20,
    durationMax: 30,
    basePriority: 4,
    requiredWorkers: 1,
    requiredEquipment: ["cleaning_kit"],
    fatigueIncrement: 0.08,
    healthDeltaOnComplete: 5,
    moodDeltaOnComplete: 5,
    patienceRestore: 22,
  },
  diaper_change: {
    labelZh: "换尿布",
    taskClass: "heavy",
    durationMin: 12,
    durationMode: 18,
    durationMax: 25,
    basePriority: 4,
    requiredWorkers: 1,
    requiredEquipment: ["cleaning_kit"],
    fatigueIncrement: 0.08,
    healthDeltaOnComplete: 4,
    moodDeltaOnComplete: 4,
    patienceRestore: 22,
  },
  transfer: {
    labelZh: "床椅转移",
    taskClass: "heavy",
    durationMin: 15,
    durationMode: 24,
    durationMax: 30,
    basePriority: 5,
    requiredWorkers: 2,
    requiredEquipment: ["wheelchair"],
    fatigueIncrement: 0.09,
    healthDeltaOnComplete: 4,
    moodDeltaOnComplete: 3,
    patienceRestore: 24,
  },
  emergency_call: {
    labelZh: "紧急呼叫",
    taskClass: "heavy",
    durationMin: 8,
    durationMode: 14,
    durationMax: 20,
    basePriority: 5,
    requiredWorkers: 1,
    requiredEquipment: [],
    fatigueIncrement: 0.075,
    healthDeltaOnComplete: 8,
    moodDeltaOnComplete: 2,
    patienceRestore: 30,
  },
};

const PEAK_TASK_POOL = {
  full_day: {
    patrol: 0.12,
    water: 0.1,
    fetch_item: 0.08,
    medication: 0.11,
    feeding: 0.13,
    toileting: 0.14,
    turning: 0.1,
    cleaning: 0.08,
    diaper_change: 0.06,
    transfer: 0.04,
    emergency_call: 0.04,
  },
  morning_peak: {
    patrol: 0.05,
    water: 0.05,
    fetch_item: 0.05,
    medication: 0.1,
    feeding: 0,
    toileting: 0.2,
    turning: 0.1,
    cleaning: 0.15,
    diaper_change: 0.15,
    transfer: 0.1,
    emergency_call: 0.05,
  },
  midday_peak: {
    patrol: 0.05,
    water: 0.08,
    fetch_item: 0.04,
    medication: 0.12,
    feeding: 0.25,
    toileting: 0.18,
    turning: 0.08,
    cleaning: 0.06,
    diaper_change: 0.06,
    transfer: 0.04,
    emergency_call: 0.04,
  },
  evening_peak: {
    patrol: 0.04,
    water: 0.04,
    fetch_item: 0.04,
    medication: 0.08,
    feeding: 0.18,
    toileting: 0.12,
    turning: 0.18,
    cleaning: 0.14,
    diaper_change: 0.12,
    transfer: 0.08,
    emergency_call: 0.04,
  },
  evening_intensive: {
    patrol: 0.02,
    water: 0.03,
    fetch_item: 0.03,
    medication: 0.06,
    feeding: 0.18,
    toileting: 0.1,
    turning: 0.18,
    cleaning: 0.16,
    diaper_change: 0.14,
    transfer: 0.14,
    emergency_call: 0.06,
  },
};

const CARE_MODE_PRIORITY_WEIGHTS = {
  moral_care: {
    healthRisk: 0.3,
    patienceRisk: 0.15,
    taskUrgency: 0.2,
    waitingTimeRisk: 0.15,
    careLevelWeight: 0.15,
    escalationBonus: 0.2,
    relationalBonus: 0.05,
    distanceCost: 0.08,
    fatiguePenalty: 0.06,
    equipmentPenalty: 0.1,
  },
  practical_care: {
    healthRisk: 0.15,
    patienceRisk: 0.1,
    taskUrgency: 0.15,
    waitingTimeRisk: 0.15,
    careLevelWeight: 0.1,
    escalationBonus: 0.1,
    relationalBonus: 0.02,
    distanceCost: 0.25,
    fatiguePenalty: 0.12,
    equipmentPenalty: 0.15,
  },
  relational_care: {
    healthRisk: 0.18,
    patienceRisk: 0.18,
    taskUrgency: 0.12,
    waitingTimeRisk: 0.12,
    careLevelWeight: 0.1,
    escalationBonus: 0.12,
    relationalBonus: 0.25,
    distanceCost: 0.1,
    fatiguePenalty: 0.08,
    equipmentPenalty: 0.1,
  },
};

const FATIGUE_CONFIG = {
  lightTaskIncrement: 0.01,
  mediumTaskIncrement: 0.035,
  heavyTaskIncrement: 0.08,
  transferTaskIncrement: 0.09,
  walkingIncrementPer50M: 0.01,
  idleRecoveryPerTick: 0.002,
  lightTaskRecoveryPerTick: 0.001,
  unavailableThreshold: 0.85,
  warningThreshold: 0.65,
};

const EQUIPMENT_POOL_DEFAULT = {
  wheelchair: { labelZh: "轮椅", total: 3, storageTile: { x: 20, y: 23 } },
  commode_trolley: { labelZh: "坐便推车", total: 2, storageTile: { x: 20, y: 23 } },
  medicine_cart: { labelZh: "药车", total: 1, storageTile: { x: 20, y: 23 } },
  cleaning_kit: { labelZh: "清洁包", total: 3, storageTile: { x: 20, y: 23 } },
};

function envBoolean(name, fallback) {
  const value = process.env[name];
  if (value === undefined) return fallback;
  if (/^(1|true|yes|on)$/i.test(value)) return true;
  if (/^(0|false|no|off)$/i.test(value)) return false;
  return fallback;
}

function envChoice(name, fallback, choices) {
  const value = process.env[name];
  return choices.includes(value) ? value : fallback;
}

const DEFAULT_CONFIG = {
  randomSeed: 42,
  durationTicks: 120,
  simulationDays: 1,
  tickMinutes: 1,
  simSpeed: 40,
  peakWindow: "morning_peak",
  shift: "day_shift",
  congestion: "medium",
  layout: "u_shape_40_rooms",
  workerCount: 6,
  wingDistribution: "balanced",
  oneToOneDay: 6,
  oneToOneFullDay: 2,
  nightWorkerCount: 2,
  seniorCount: 40,
  careLevel1Ratio: 40,
  careLevel2Ratio: 35,
  careLevel3Ratio: 25,
  autoNormalizeCareLevel: true,
  demandIntensity: "medium",
  manualGenerateCount: 3,
  careMode: "practical_care",
  agentDecisionMode: envChoice("CYBERNH_DEFAULT_AGENT_DECISION_MODE", "llm_required", [
    "rule_only",
    "llm_required",
  ]),
  workerAgentLlmEnabled: envBoolean("CYBERNH_DEFAULT_WORKER_AGENT_LLM_ENABLED", true),
  seniorAgentLlmEnabled: envBoolean("CYBERNH_DEFAULT_SENIOR_AGENT_LLM_ENABLED", false),
  assistantAgentEnabled: true,
  escalationThresholdTicks: 10,
  maxPendingDemand: 10,
  maxActiveTask: 6,
  twoPersonTaskEnabled: true,
  interruptionEnabled: true,
};

module.exports = {
  TILE_SIZE_M,
  GRID_COLS,
  GRID_ROWS,
  LAYOUT_CONFIG,
  PEAK_WINDOWS,
  CONGESTION_CONFIG,
  SHIFT_CONFIG,
  DAY_WORKER_INITIAL_POSITIONS,
  NIGHT_WORKER_INITIAL_POSITIONS,
  DEFAULT_WORKER_PROFILE,
  SENIOR_DISTRIBUTION_DEFAULT,
  CARE_LEVEL_TASK_PROBABILITY,
  SENIOR_INITIAL_STATUS,
  DEMAND_INTENSITY_CONFIG,
  TASK_CATALOG,
  PEAK_TASK_POOL,
  CARE_MODE_PRIORITY_WEIGHTS,
  FATIGUE_CONFIG,
  EQUIPMENT_POOL_DEFAULT,
  DEFAULT_CONFIG,
};
